class MESSAGE_CODE:
    NOT_FOUND: str = "NOT_FOUND"
    UNAUTHORIZED: str = "UNAUTHORIZED"
    FORBIDDEN: str = "FORBIDDEN"
    BAD_REQUEST: str = "BAD_REQUEST"
    CREATED: str = "CREATED"
    SUCCESS: str = "SUCCESS"
    INTERNAL_SERVER_ERROR: str = "ERROR"
